mod test_utils;

use anyhow::Result;
use chrono::Utc;
use miden_client::crypto::FeltRng;
use miden_client::{
    Word,
    asset::FungibleAsset,
    note::{NoteAssets, NoteDetails, NoteTag, NoteType},
    transaction::{OutputNote, TransactionRequestBuilder},
};
use test_utils::*;
use zoroswap::{
    create_expected_p2id_recipient, create_zoroswap_note, fetch_pool_state_from_chain,
    fetch_vault_for_account_from_chain, get_oracle_prices, print_note_info,
    print_transaction_info,
};

#[tokio::test]
async fn e2e_public_note() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter("info,zoro=debug")
        .init();

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 0] Init client and config\n");

    // Use a fresh store to avoid leftover data from prior test runs.
    let store_path = "../../public_test_store.sqlite3";
    let _ = std::fs::remove_file(store_path);

    let mut setup = setup_test_environment(store_path).await?;
    let account = setup.account.clone();
    let pool0 = setup.pools[0];
    let pool1 = setup.pools[1];

    let (balances_pool_0, _) = fetch_pool_state_from_chain(
        &mut setup.client,
        setup.config.pool_account_id,
        pool0.faucet_id,
    )
    .await?;
    let (balances_pool_1, _) = fetch_pool_state_from_chain(
        &mut setup.client,
        setup.config.pool_account_id,
        pool1.faucet_id,
    )
    .await?;
    let vault =
        fetch_vault_for_account_from_chain(&mut setup.client, setup.config.pool_account_id)
            .await?;
    println!("balances for liq pool 0: {balances_pool_0:?}");
    println!("balances for liq pool 1: {balances_pool_1:?}");
    println!("pool vault on-chain: {vault:?}");

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 1] Fund user wallet\n");
    fund_user_wallet(&mut setup.client, &account, &pool0, None).await?;

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 2] Fetching latest prices from the oracle\n");

    let prices = get_oracle_prices(
        setup.config.oracle_https,
        vec![pool0.oracle_id, pool1.oracle_id],
    )
    .await?;
    let pool0_price = extract_oracle_price(&prices, pool0.oracle_id, pool0.symbol)?;
    let pool1_price = extract_oracle_price(&prices, pool1.oracle_id, pool1.symbol)?;

    println!(
        "Latest prices {}: {} usd, {}: {} usd",
        pool0.symbol, pool0_price, pool1.symbol, pool1_price
    );

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 3] Create user zoroswap note\n");
    let amount_in = 3 * 10u64.pow(pool0.decimals as u32 - 2); // 0.03
    let max_slippage = 0.005; // 0.5 %
    let min_amount_out =
        ((pool0_price as f64) / (pool1_price as f64)) * (amount_in as f64) * (1.0 - max_slippage);
    let min_amount_out = min_amount_out as u64;
    let asset_in = FungibleAsset::new(pool0.faucet_id, amount_in)?;
    let asset_out = FungibleAsset::new(pool1.faucet_id, min_amount_out)?;
    let requested_asset_word: Word = asset_out.into();
    let p2id_tag = NoteTag::with_account_target(account.id());
    let deadline = (Utc::now().timestamp_millis() as u64) + 120000;

    let inputs = build_zoroswap_inputs(
        requested_asset_word,
        deadline,
        p2id_tag,
        account.id(),
        account.id(),
    );
    let zoroswap_serial_num = setup.client.rng().draw_word();
    println!(
        "Made an order note requesting {amount_in} {} for at least {min_amount_out} {}.",
        pool0.symbol, pool1.symbol
    );
    let zoroswap_note = create_zoroswap_note(
        inputs,
        vec![asset_in.into()],
        account.id(),
        zoroswap_serial_num,
        NoteTag::with_account_target(setup.config.pool_account_id),
        NoteType::Public,
    )?;

    // Create the expected P2ID recipient that will be generated by the ZOROSWAP script
    let expected_p2id_recipient =
        create_expected_p2id_recipient(zoroswap_serial_num, account.id())?;

    // Create `NoteDetails` for the expected P2ID note that will be created when
    // the ZOROSWAP note is consumed
    let p2id_assets = NoteAssets::new(vec![asset_out.into()])?;
    let p2id_note_details = NoteDetails::new(p2id_assets, expected_p2id_recipient.clone());
    let p2id_tag = NoteTag::with_account_target(account.id());

    let note_req = TransactionRequestBuilder::new()
        .own_output_notes(vec![OutputNote::Full(zoroswap_note.clone())])
        .expected_future_notes(vec![(p2id_note_details, p2id_tag)])
        .build()
        .unwrap();

    let tx_id = setup
        .client
        .submit_new_transaction(account.id(), note_req)
        .await
        .unwrap();

    print_transaction_info(&tx_id);
    print_note_info(&zoroswap_note.id());

    setup.client.sync_state().await?;

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 4] Wait for notes back\n");
    println!("Waiting for consumable note for {account:?}");
    let consumable_notes =
        zoro_miden_client::wait_for_consumable_notes(&mut setup.client, account.id()).await?;
    println!(
        "Received {} consumable notes (p2id) on client.",
        consumable_notes.len()
    );

    assert!(
        consumable_notes.iter().any(|note| note.recipient().digest() == expected_p2id_recipient.digest()),
        "None of the received notes matched the expected P2ID recipient"
    );

    println!(
        "Expected account with suffix: {:?}, prefix: {:?}",
        account.id().suffix(),
        account.id().prefix().as_felt()
    );

    let consume_req = TransactionRequestBuilder::new()
        .build_consume_notes(consumable_notes)
        .unwrap();

    let tx_id = setup
        .client
        .submit_new_transaction(account.id(), consume_req)
        .await?;
    setup.client.sync_state().await?;
    let new_balance_user =
        fetch_vault_for_account_from_chain(&mut setup.client, account.id()).await?;
    println!("New account vault: {:?}", new_balance_user);
    println!("User successfully consumed swap into its wallet.");
    print_transaction_info(&tx_id);

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 5] Confirm pool states updated accordingly\n");
    assert_pool_states_changed(
        &mut setup.client,
        setup.config.pool_account_id,
        pool0.faucet_id,
        pool1.faucet_id,
        &balances_pool_0,
        &balances_pool_1,
        &vault,
    )
    .await?;

    Ok(())
}
