mod test_utils;

use anyhow::Result;
use chrono::Utc;
use miden_client::crypto::FeltRng;
use miden_client::{
    Word,
    asset::FungibleAsset,
    note::{NoteAssets, NoteDetails, NoteTag, NoteType},
    transaction::{OutputNote, TransactionRequestBuilder},
};
use test_utils::*;
use zoro_miden::account::MidenAccount;
use zoro_miden::client::MidenClient;
use zoro_miden::note::{TrustedNote, create_expected_p2id_recipient};
use zoroswap::{
    fetch_pool_state_from_chain, fetch_vault_for_account_from_chain, get_oracle_prices,
};

#[tokio::test]
async fn e2e_public_note() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter("info,zoro=debug")
        .init();

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 0] Init client and config\n");

    // Use a fresh store to avoid leftover data from prior test runs.
    let store_path = "../../public_test_store.sqlite3";
    let _ = std::fs::remove_file(store_path);

    let E2ETestSetup {
        config,
        client: mut miden_client,
        keystore,
        zoro_pool,
    } = E2ETestSetup::new(store_path).await?;
    let account = MidenAccount::deploy_new(&mut miden_client, keystore).await?;

    let pool0 = pools[0];
    let pool1 = pools[1];

    zoro_pool.print_pool_state();

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 1] Fund user wallet\n");
    let amount = 500000;
    miden_client.mint_asset(pool0.faucet_id, *account.id(), amount);

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 2] Fetching latest prices from the oracle\n");
    let prices =
        get_oracle_prices(config.oracle_https, vec![pool0.oracle_id, pool1.oracle_id]).await?;
    let pool0_price = extract_oracle_price(&prices, pool0.oracle_id, pool0.symbol)?;
    let pool1_price = extract_oracle_price(&prices, pool1.oracle_id, pool1.symbol)?;

    println!(
        "Latest prices {}: {} usd, {}: {} usd",
        pool0.symbol, pool0_price, pool1.symbol, pool1_price
    );

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 3] Send zoroswap note\n");
    let amount_in = 3 * 10u64.pow(pool0.decimals as u32 - 2); // 0.03
    let max_slippage = 0.005; // 0.5 %
    let min_amount_out =
        ((pool0_price as f64) / (pool1_price as f64)) * (amount_in as f64) * (1.0 - max_slippage);
    let min_amount_out = min_amount_out as u64;
    let asset_in = FungibleAsset::new(pool0.faucet_id, amount_in)?;
    let asset_out = FungibleAsset::new(pool1.faucet_id, min_amount_out)?;
    let requested_asset_word: Word = asset_out.into();
    let p2id_tag = NoteTag::with_account_target(*account.id());
    let deadline = (Utc::now().timestamp_millis() as u64) + 120000;

    let inputs = build_zoroswap_inputs(
        requested_asset_word,
        deadline,
        p2id_tag,
        *account.id(),
        *account.id(),
    );
    let zoroswap_serial_num = miden_client.client_mut().rng().draw_word();
    println!(
        "Made an order note requesting {amount_in} {} for at least {min_amount_out} {}.",
        pool0.symbol, pool1.symbol
    );
    let zoroswap_note = TrustedNote::new_swap(
        inputs,
        vec![asset_in.into()],
        *account.id(),
        zoroswap_serial_num,
        NoteTag::with_account_target(config.pool_account_id),
        NoteType::Public,
    )
    .await?;

    // Create the expected P2ID recipient that will be generated by the ZOROSWAP script
    let expected_p2id_recipient = account.zoro_swap_p2id_recipient(zoroswap_serial_num)?;

    let p2id_assets = NoteAssets::new(vec![asset_out.into()])?;
    let p2id_note_details = NoteDetails::new(p2id_assets, expected_p2id_recipient);
    let p2id_tag = NoteTag::with_account_target(*account.id());

    let note_req = TransactionRequestBuilder::new()
        .own_output_notes(vec![OutputNote::Full(zoroswap_note.note().clone())])
        .expected_future_notes(vec![(p2id_note_details, p2id_tag)])
        .build()
        .unwrap();

    let tx_id = miden_client
        .client_mut()
        .submit_new_transaction(*account.id(), note_req)
        .await
        .unwrap();

    MidenClient::print_transaction_info(&tx_id);
    zoroswap_note.print_note_info();

    miden_client.sync_state().await?;

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 4] Wait for notes back\n");
    let tx = miden_client.consume_notes(account.id(), 1).await;
    let new_balance_user = account.get_balance(&pool1.faucet_id).await?;
    println!("New balance for user: {:?}", new_balance_user);
    println!("User successfully consumed swap into its wallet.");

    // ---------------------------------------------------------------------------------
    println!("\n\t[STEP 5] Confirm pool states updated accordingly\n");
    assert!(
        *old_balances_0 != new_balances_pool_0,
        "Balances for pool 0 havent changed"
    );
    assert!(
        *old_balances_1 != new_balances_pool_1,
        "Balances for pool 1 havent changed"
    );
    assert!(new_vault != *old_vault, "Vault hasn't changed");

    assert_pool_states_changed(
        &mut setup.client,
        setup.config.pool_account_id,
        pool0.faucet_id,
        pool1.faucet_id,
        &balances_pool_0,
        &balances_pool_1,
        &vault,
    )
    .await?;

    Ok(())
}
